import { adminDb } from '@/lib/firebase/admin';
import {
  createDividend,
  deleteUpcomingCouponsForAsset,
  deleteUpcomingFinalPremiumForAsset,
  getDividendById,
} from '@/lib/services/dividendService';
import { createExpenseFromDividend } from '@/lib/services/dividendIncomeService';
import { DividendFormData } from '@/types/dividend';
import { Asset } from '@/types/assets';
import { ExpenseCategory } from '@/types/expenses';

export type CreateDividendResult =
  | { skipped: true; reason: string }
  | { skipped: false; dividendId: string; expenseId?: string };

/**
 * Create a dividend entry with optional automatic expense creation.
 *
 * Orchestrates:
 *   1. Auto-generated coupon/finalPremium cleanup (prevents duplicate upcoming entries)
 *   2. costPerShare enrichment for accurate historical YOC
 *   3. Dividend creation via dividendService
 *   4. Conditional expense creation if paymentDate <= today and user has
 *      dividendIncomeCategoryId configured
 *
 * Returns { skipped: true } when an auto-generated entry for a sold asset
 * (quantity === 0) triggers cleanup but no new entry should be created.
 *
 * Ownership check (asset.userId === userId) must be performed by the caller
 * before invoking this function.
 */
export async function createDividendWithOptionalExpense(
  userId: string,
  dividendData: DividendFormData,
  asset: Asset & { id: string }
): Promise<CreateDividendResult> {
  // Cleanup stale auto-generated entries before creating a new one.
  // Prevents duplicate upcoming coupons when bond details are updated.
  if (dividendData.dividendType === 'coupon' && dividendData.isAutoGenerated) {
    await deleteUpcomingCouponsForAsset(userId, dividendData.assetId);
    // Asset sold: cleanup done, no new zero-amount entry needed
    if ((dividendData.quantity ?? 1) === 0) {
      return { skipped: true, reason: 'Upcoming coupons cleaned up; no new entry created (asset sold)' };
    }
  }
  if (dividendData.dividendType === 'finalPremium' && dividendData.isAutoGenerated) {
    await deleteUpcomingFinalPremiumForAsset(userId, dividendData.assetId);
    // Asset sold: cleanup done, no new zero-amount entry needed
    if ((dividendData.quantity ?? 1) === 0) {
      return { skipped: true, reason: 'Final premium cleaned up; no new entry created (asset sold)' };
    }
  }

  // Enrich with costPerShare snapshot for accurate historical YOC
  const enrichedDividendData: DividendFormData = {
    ...dividendData,
    costPerShare: asset.averageCost,
  };

  const dividendId = await createDividend(
    userId,
    enrichedDividendData,
    asset.ticker,
    asset.name,
    asset.isin,
    enrichedDividendData.isAutoGenerated
  );

  // ========== Conditional Expense Creation ==========
  //
  // Create expense immediately if dividend already paid (paymentDate <= today).
  // Future dividends are processed by the daily cron job on payment date.
  // This ensures manual historical entries have immediate cashflow impact.
  // Wrap in new Date() because paymentDate arrives as a JSON string from the client,
  // and string <= Date comparisons always return false in JavaScript.
  const paymentDate = new Date(dividendData.paymentDate);
  const today = new Date();
  today.setHours(23, 59, 59, 999);

  let expenseId: string | undefined;

  if (paymentDate <= today) {
    expenseId = await createExpenseIfConfigured(userId, dividendId);
  }

  return { skipped: false, dividendId, expenseId };
}

/**
 * Create a cashflow expense for a dividend if the user has
 * dividendIncomeCategoryId configured in their settings.
 *
 * Non-fatal: returns undefined (and logs) if expense creation fails.
 * The dividend record is the primary operation; expense is secondary.
 */
async function createExpenseIfConfigured(
  userId: string,
  dividendId: string
): Promise<string | undefined> {
  try {
    const settingsDoc = await adminDb
      .collection('assetAllocationTargets')
      .doc(userId)
      .get();

    const settings = settingsDoc.exists ? settingsDoc.data() : null;
    if (!settings?.dividendIncomeCategoryId) return undefined;

    const categoryDoc = await adminDb
      .collection('expenseCategories')
      .doc(settings.dividendIncomeCategoryId)
      .get();

    if (!categoryDoc.exists) return undefined;

    const categoryData = categoryDoc.data() as ExpenseCategory;
    const category = { ...categoryData, id: categoryDoc.id };

    let subCategoryName: string | undefined;
    if (settings.dividendIncomeSubCategoryId) {
      const subCategory = category.subCategories?.find(
        (sub: any) => sub.id === settings.dividendIncomeSubCategoryId
      );
      subCategoryName = subCategory?.name;
    }

    const dividend = await getDividendById(dividendId);
    if (!dividend) return undefined;

    return await createExpenseFromDividend(
      dividend,
      settings.dividendIncomeCategoryId,
      category.name,
      settings.dividendIncomeSubCategoryId,
      subCategoryName
    );
  } catch (error) {
    // Non-critical: dividend creation already succeeded; expense is best-effort
    console.error('[createExpenseIfConfigured] Error creating expense from dividend:', error);
    return undefined;
  }
}
